const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { getOrCreateUser, saveUser } = require('../../utils/db');
const { getGangByMember, saveGang } = require('../../utils/gangDb');
const { noAccount } = require('../../utils/accountCheck');
const { COLORS } = require('../../utils/embeds');

// Upgrade tiers
const UPGRADES = {
  mafia: {
    name: 'Become a Mafia',
    emoji: '👔',
    cost: 50000,
    repRequired: 500,
    winsRequired: 5,
    desc: 'Transform your street gang into a full Mafia operation. Unlocks extortion, money laundering, contract hits, smuggling, and police bribery. Gang bank cut increases. Police on payroll reduces heat and arrest chances.',
    perks: ['Mafia-exclusive crimes unlocked', 'Higher gang bank cut (up to 30%)', 'Police bribery reduces heat by 25+', 'Assassination missions available', 'Smuggling runs for massive payouts'],
  },
  police_payroll: {
    name: 'Police on Payroll',
    emoji: '👮',
    cost: 20000,
    repRequired: 200,
    winsRequired: 0,
    mafiaOnly: false,
    desc: 'Pay local officers to look the other way. Each level reduces arrest chance by 5% and heat generated by 3 per crime.',
    maxLevel: 5,
    levelCost: 20000,
  },
  armory: {
    name: 'Gang Armory',
    emoji: '🔫',
    cost: 15000,
    repRequired: 150,
    winsRequired: 3,
    desc: 'Upgrade your arsenal. Increases war attack points and success rate.',
    maxLevel: 5,
    levelCost: 15000,
    warBonus: 5,
  },
  safehouses: {
    name: 'Safehouses',
    emoji: '🏠',
    cost: 25000,
    repRequired: 300,
    desc: 'Establish safehouses across the city. Reduces jail time by 30% per level.',
    maxLevel: 3,
    levelCost: 25000,
  },
};

module.exports = {
  data: new SlashCommandBuilder()
    .setName('gangupgrade')
    .setDescription('Upgrade your gang\'s capabilities.')
    .addStringOption(o => o.setName('upgrade').setDescription('Upgrade to purchase').setRequired(true)
      .addChoices(
        { name: '👔 Become a Mafia ($50,000 · 500 rep · 5 wins)', value: 'mafia' },
        { name: '👮 Police on Payroll ($20,000/level · max 5)', value: 'police_payroll' },
        { name: '🔫 Gang Armory ($15,000/level · max 5)', value: 'armory' },
        { name: '🏠 Safehouses ($25,000/level · max 3)', value: 'safehouses' },
      )
    ),

  async execute(interaction) {
    if (await noAccount(interaction)) return;
    const userId    = interaction.user.id;
    const upgradeId = interaction.options.getString('upgrade');
    const upgrade   = UPGRADES[upgradeId];
    const gang      = getGangByMember(userId);

    if (!gang) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription("You're not in a gang.")], ephemeral: true });
    if (gang.leaderId !== userId) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription("Only the gang leader can purchase upgrades.")], ephemeral: true });

    // Mafia conversion
    if (upgradeId === 'mafia') {
      if (gang.gangType === 'mafia') return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x888888).setDescription("Your gang is already a Mafia.")], ephemeral: true });
      if ((gang.rep||0) < upgrade.repRequired) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription(`You need **${upgrade.repRequired} rep** to go Mafia. You have **${gang.rep||0}**.`)], ephemeral: true });
      if ((gang.wins||0) < upgrade.winsRequired) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription(`You need **${upgrade.winsRequired} war wins** to go Mafia. You have **${gang.wins||0}**.`)], ephemeral: true });
      if (gang.bank < upgrade.cost) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription(`Gang bank needs **$${upgrade.cost.toLocaleString()}**. You have **$${gang.bank.toLocaleString()}**.`)], ephemeral: true });

      gang.bank     -= upgrade.cost;
      gang.gangType  = 'mafia';
      saveGang(gang.id, gang);

      return interaction.reply({ embeds: [new EmbedBuilder()
        .setColor(0x2c3e50)
        .setTitle('👔 The Family Has Arrived')
        .setDescription(`**${gang.name}** is now a **Mafia**.\n\nNew crimes unlocked: Extortion, Money Laundering, Contract Hits, Smuggling, Police Bribery, Assassination.\n\nCost: **$${upgrade.cost.toLocaleString()}** from gang bank.`)
        .addFields({ name: '🎯 Perks', value: upgrade.perks.map(p=>`• ${p}`).join('\n') })
      ]});
    }

    // Level-based upgrades
    const currentLevel = gang[upgradeId] || 0;
    const maxLevel     = upgrade.maxLevel || 1;
    if (currentLevel >= maxLevel) return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x888888).setDescription(`**${upgrade.name}** is already at max level (${maxLevel}).`)], ephemeral: true });

    const cost = upgrade.levelCost * (currentLevel + 1);
    if (gang.bank < cost) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription(`Gang bank needs **$${cost.toLocaleString()}** for level ${currentLevel+1}. You have **$${gang.bank.toLocaleString()}**.`)], ephemeral: true });
    if ((gang.rep||0) < (upgrade.repRequired||0)) return interaction.reply({ embeds: [new EmbedBuilder().setColor(COLORS.ERROR).setDescription(`Need **${upgrade.repRequired} rep** for this upgrade.`)], ephemeral: true });

    gang.bank -= cost;
    gang[upgradeId] = currentLevel + 1;
    saveGang(gang.id, gang);

    const perks = {
      police_payroll: `Arrest chance -${(currentLevel+1)*5}% · Heat per crime -${(currentLevel+1)*3}`,
      armory:         `War attack points +${(currentLevel+1)*5} · Success rate +${(currentLevel+1)*5}%`,
      safehouses:     `Jail time -${(currentLevel+1)*30}%`,
    };

    return interaction.reply({ embeds: [new EmbedBuilder()
      .setColor(0xf5c518)
      .setTitle(`${upgrade.emoji} ${upgrade.name} — Level ${currentLevel+1}`)
      .setDescription(`Upgraded **${upgrade.name}** to Level **${currentLevel+1}/${maxLevel}**!\n\n${perks[upgradeId]}\n\nCost: **$${cost.toLocaleString()}** from gang bank.`)
    ]});
  },
};
